# coding: utf-8

"""
    GroupDocs.Classification Cloud API References

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 19.3

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from test import BaseTestContext


class TestSupportedFileFormats(BaseTestContext):
    """ get_supported_file_formats unit test stubs """

    def test_get_supported_file_formats(self):
        """
        Test get_supported_file_formats
        """
        result = self.classification_api.get_supported_file_formats(None)
        print("Result {}".format(result))