# coding: utf-8

"""
    GroupDocs.Classification Cloud API References

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 19.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

from os.path import join
import unittest

from groupdocsclassificationcloud import BaseRequest, ClassifyRequest, FileInfo
from test import BaseTestContext


class TestClassify(BaseTestContext):
    """ Classify unit test stubs """

    def test_classify(self):
        """
        Test classify
        """
        request = ClassifyRequest(BaseRequest("Try text classification"), 3)
        result = self.classification_api.classify(request)
        print(result)

    def test_classify_document(self):
        """
        Test classify document
        """

        filename = 'test_multi_pages.docx'
        file_path = join(self.local_common_folder, filename)
        with open(file_path, 'rb') as f:
            file_data = f.read()

        file_upload_response = self.storage_api.put_create(self.remote_test_folder + '/' + filename, file_data)
        # Check if file uploaded successfully to Cloud Storage
        if (file_upload_response["code"] == 200 and file_upload_response["status"] == "OK"):
            request = ClassifyRequest(BaseRequest(document=FileInfo(name=filename, folder=self.remote_test_folder)))
            result = self.classification_api.classify(request)
            print("Result {}".format(result))

        request = ClassifyRequest(BaseRequest("Try text classification"), 3)
        result = self.classification_api.classify(request)
        print(result)
